name: tutorial-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - xarray
  - cartopy
  - statsmodels
  - netcdf4
  - rpy2
  - r-base=4.0.3
  - r-tidyverse
  - r-essentials
